name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create Dist Directory (if it doesn’t exist)
      - name: Create Dist Directory
        run: mkdir -p dist

      # Step 3: Generate the Default Snake Graph
      - name: Generate Default Snake Graph
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg

      # Step 4: Generate the Dark Snake Graph
      - name: Generate Dark Snake Graph
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake-dark.svg?palette=github-dark

      # Step 5: Commit the Generated Files
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated Snake Contribution Graph"
          branch: main
          file_pattern: "dist/github-snake.svg dist/github-snake-dark.svg"
